name: cl_weather_app
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: 1.0.4
  dio: 4.0.4
  equatable: 2.0.3
  flutter_bloc: 8.0.1
  flutter:
    sdk: flutter
  get_it: 7.2.0
  shimmer: 2.0.0
  flutter_svg: 1.0.3
  permission_handler: 9.2.0
  geolocator: 8.2.0
  json_annotation: 4.4.0
  flutter_screenutil: 5.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: 9.0.3
  lints: 1.0.1
  mockito: 5.1.0
  build_runner: 2.1.8
  json_serializable: 6.1.5
  flutter_launcher_icons: 0.9.2

flutter:
  uses-material-design: true
  assets:
    - res/assets/
    - res/fonts/

fonts:
  - family: Roboto
    fonts:
      - asset: res/fonts/Roboto-Thin.ttf
        weight: 100
      - asset: res/fonts/Roboto-Thin.ttf
        weight: 200
      - asset: res/fonts/Roboto-Light.ttf
        weight: 300
      - asset: res/fonts/Roboto-Regular.ttf
        weight: 400
      - asset: res/fonts/Roboto-Medium.ttf
        weight: 500
      - asset: res/fonts/Roboto-Semibold.ttf
        weight: 600
      - asset: res/fonts/Roboto-Bold.ttf
        weight: 700
      - asset: res/fonts/Roboto-Black.ttf
        weight: 800
      - asset: res/fonts/Roboto-Black.ttf
        weight: 900

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "res/assets/icon.png"