name: Test Code Flow

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: 'Get dependencies'
        run: flutter pub get

      - name: 'Code generation'
        run: flutter pub run build_runner build

      - name: 'Check code style'
        run: flutter format --set-exit-if-changed .

      - name: 'Analyze'
        run: flutter analyze

      - name: 'Tests'
        run: flutter test

      - name: 'Dart Code Metrics'
        run: flutter pub run dart_code_metrics:metrics analyze lib