name: Upload android build to Firebase App Distribution

on:
  push:
    branches:
      - upload

jobs:
  android:
    name: Release android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Get Dependencies
       run: flutter pub get

      - name: Generate code
      run: flutter pub run build_runner build

      - name: Build APK
      run: flutter build apk --debug

      - name: Upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        file: build/app/outputs/flutter-apk/app-debug.apk