name: Upload ios build to Firebase App Distribution

on:
  push:
    branches:
      - upload

jobs:
  ios:
    name: Upload ios
    runs-on: macos-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Java'
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: 'Install Flutter'
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          cache: true

      - name: 'Get dependencies'
        run: flutter pub get

      - name: 'Code generation'
        run: flutter pub run build_runner build

      - name: 'Build IPA'
        run: flutter build ios --no-codesign

      - name: Sign ios build
        uses: yukiarrr/ios-build-action@v1.5.0
        with:
          export-method: app-store
          project-path: ios/Runner.xcodeproj
          workspace-path: ios/Runner.xcworkspace
          output-path: 'Runner.ipa'
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}

      - name: Upload ios to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: Runner.ipa